#!/bin/bash

# 更新系统软件包
yum update -y

# 安装编译工具、依赖库和 Python
yum install -y make automake gcc gcc-c++ kernel-devel git wget python3 python3-devel python3-pip

# 安装 conan
pip3 install conan==1.59.0 --user

# 安装 Git 和 CMake
yum install -y git cmake

# 安装软件包管理工具
yum install -y epel-release

# 添加 Intel 仓库和 Key
wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list

# 更新软件包索引并安装 Intel MKL
yum update -y
yum install -y intel-oneapi-mkl

# 添加 Kitware 仓库和 Key
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/kitware.list

# 更新软件包索引并安装 CMake 和 SWIG
yum update -y
yum install -y cmake swig

# 安装 Python NumPy
pip3 install numpy

# 安装 Linux 性能分析工具和 Vim
yum install -y perf vim

# 添加自定义脚本并赋予执行权限
cp run.sh /home/faiss/
chmod a+x /home/faiss/run.sh

# 克隆知乎开源库
git clone https://github.com/milvus-io/knowhere.git /home/knowhere/

# 切换到 faiss 目录
cd /home/faiss/
